### ISSUE TITLE
[Bug]har制作页面复制时会复制了格式

### ISSUE THREAD

**Issue by ss7458** [a76yyyy/qiandao#12]
har制作页面对于某些想要复制时会复制到带格式的值
粘贴后导致页面稀烂,每次粘贴只能使用ctrl+shitf+v一点多不爽

**Comment by a76yyyy** [comment]
很抱歉，虽然会影响效率，但这确实是浏览器的问题

**Comment by a76yyyy** [comment]
已强制纯文本格式编辑，请强制更新源码并清空浏览器缓存后查看
