### ISSUE TITLE
插入 unicode转换  的网站端口为8923导致网页错误500

### ISSUE THREAD

**Issue by a1257415590** [a76yyyy/qiandao#16]
插入 unicode转换  的网站端口为8923导致网页错误500
将8923改为80可解决

**Comment by a76yyyy** [comment]
框架中插入api请求的端口判断方式为当前浏览器内所用的端口，由于Docker环境部署下通常会将80端口映射为8923端口，因此使用浏览器访问`http://localhost:8923`进行操作时，会使框架向容器内部8923端口发送请求而不是向80端口发送请求。

事实上，这是一个前端js脚本逻辑上的bug，后续会考虑修改

**Comment by a76yyyy** [comment]
已修改api策略，采用api:// 作为签到API默认scheme 参见 qiandao-today/qiandao#168
请等待发布新版本或者使用`sh ./update.sh -f && pip install -r requirements.txt`强制更新源码并清空浏览器缓存后使用
