### ISSUE TITLE
[Feature]加一个外部新建任务时自动提取default值

### ISSUE THREAD

**Issue by ss7458** [a76yyyy/qiandao#29]
**对问题本身清晰而简洁的描述. 例如, 当发生[...]时, 这令我很烦恼.**
- 看标题

**清晰明了地描述您的解决方案.**
- 不想描述，给你留着想象空间

**对您考虑过的任何替代解决方案或备选功能进行清晰、简洁的描述.**
- 没有

**在此处添加有关功能请求的任何其他描述或屏幕截图.**
- 搞快点

**Comment by a76yyyy** [comment]
功能已添加, 有问题请 reopen 这个 issue
