### ISSUE TITLE
[Bug]无脑添加`|urlencode`的问题

### ISSUE THREAD

**Issue by ss7458** [a76yyyy/qiandao#6]
例如我要写一条涉及加法的任务行
http://localhost/util/unicode?content={{12|int+num|int}}
写完-->save-->重新打开
任务行会变成
http://localhost/util/unicode?content={{122|int num|int|urlencode}}
自动删除加号并加上`|urlencode`
每次修改都会重置,非常麻烦

**Comment by a76yyyy** [comment]
已尝试修复|urlencode重复添加问题，请更新源码后重启容器并清空浏览器缓存

**Comment by a76yyyy** [comment]
加法api请尝试使用`{{add(12,num)|int}}`而不是`{{12|int+num|int}}`

![image](https://user-images.githubusercontent.com/56478790/135085030-ca29cde3-eb59-4c1f-b19f-dc07607b66b0.png)

![image](https://user-images.githubusercontent.com/56478790/135085309-5131dc56-0456-4634-93d7-22d6709fc0c6.png)

![image](https://user-images.githubusercontent.com/56478790/135085413-b0c08138-ca73-4de2-ae95-c4eb05d6ddd3.png)
